# Generated by Django 2.1.2 on 2018-10-07 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2018, 10, 7, 20, 16, 36, 589223))),
            ],
        ),
    ]
