# Generated by Django 2.1.2 on 2018-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratedata',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
