# Generated by Django 2.1.1 on 2018-10-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rateData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
